projects:
  dex:
    schemaPath: generated/dex.graphql
    extensions:
      prisma: prisma.yml
      # codegen: 
      #   - generator: prisma-binding
      #     language: typescript
      #     output:
      #       binding: generated/dex.ts
      endpoints:
        default: http://localhost:4000/dex
  wrapper:
    schemaPath: generated/wrapper.graphql
    extensions:
      prisma: prisma.yml
      # codegen: 
      #   - generator: prisma-binding
      #     language: typescript
      #     output:
      #       binding: generated/wrapper.ts
      endpoints:
        default: http://localhost:4000/wrap
 